services:
  coffee-shop:
    image: 'milehimikey/coffee-shop:latest'
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_DATA_MONGODB_HOST=mongodb'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/coffeeshop'
      - 'SPRING_DOCKER_COMPOSE_ENABLED=false'
    depends_on:
      - mongodb
      - postgres
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=coffeeshop'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/data/db'

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=coffeeshop'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=coffeeshop'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  mongodb_data:
  postgres_data:
