services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=coffeeshop'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/data/db'

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=coffeeshop'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=coffeeshop'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'

volumes:
  mongodb_data:
  postgres_data:
