management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    metrics:
      access: read-only
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  application:
    name: coffee-shop

  # MongoDB Configuration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: coffeeshop
      username: root
      password: secret
      authentication-database: admin

  # PostgreSQL Configuration for Axon Event Store
  datasource:
    url: jdbc:postgresql://localhost:5432/coffeeshop
    username: coffeeshop
    password: secret

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: wtf.milehimikey.coffeeshop.config.ByteaEnforcedPostgresSQLDialect

  # Task scheduling configuration
  task:
    scheduling:
      pool:
        size: 5

# Server Configuration
server:
  port: 8080

# Axon Configuration
axon:
  metrics:
    auto-configuration:
      enabled: true
  axonserver:
    enabled: false
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  # Configure event sourcing repositories
  repository:
    default-snapshot-trigger-threshold: 50  # Global default snapshot threshold
  # Configure event store
  eventhandling:
    processors:
      order:
        mode: pooled
        thread-count: 8
        dlq:
          enabled: true
      payment:
        mode: pooled
        thread-count: 8
        dlq:
          enabled: true
      product:
        mode: pooled
        thread-count: 8
        dlq:
          enabled: true
