spring:
  application:
    name: coffee-shop

  # MongoDB Configuration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: coffeeshop
      username: root
      password: secret
      authentication-database: admin

  # PostgreSQL Configuration for Axon Event Store
  datasource:
    url: jdbc:postgresql://localhost:5432/coffeeshop
    username: coffeeshop
    password: secret

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: wtf.milehimikey.coffeeshop.config.ByteaEnforcedPostgresSQLDialect

  # Task scheduling configuration
  task:
    scheduling:
      pool:
        size: 5

# Server Configuration
server:
  port: 8080

# Axon Configuration
axon:
  axonserver:
    enabled: false
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  # Configure event sourcing repositories
  repository:
    default-snapshot-trigger-threshold: 50  # Global default snapshot threshold
  # Configure event store
  eventhandling:
    processors:
      order:
        mode: tracking
        thread-count: 2
      payment:
        mode: tracking
        thread-count: 1
        dlq:
          enabled: true
          max-sequence-size: 256
          processing-group: payment
